### ISSUE TITLE
bouncing proteins cause seasickness?

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#111]
Someone asked for the graphic not to render until after final positions for layout have been calculated, they don't like the bouncy effect as it lays itself out.

Possibly not high priority, most people don't seem too bothered by it...

**Comment by tschaka1904** [comment]
Maybe this can help: 
![screen shot 2017-06-06 at 14 03 15](https://cloud.githubusercontent.com/assets/5269116/26830836/0e22c37a-4ac2-11e7-9268-40ce6e32a8e1.png)

**Comment by bmeldal** [comment]
This came up again yesterday in testing with a real user at Cambridge Uni.

At the same time the user noticed that the names often stop over the edge and then become unreadable (or at least difficult to read). Is there any chance to make the names stop in space? Shall I open a new ticket for that?

**Comment by colin-combe** [comment]
OK, I should change it.

Both the bouncing and the names being over the edge are consequences of the layout algorithm. I plan to change the layout code to use the [CoLa](http://marvl.infotech.monash.edu/webcola/) library, hopefully that will help with these probs .

**Comment by bmeldal** [comment]
Thanks. Let me know when you have a demo and I'll send the link to the users that felt nauseous!

**Comment by colin-combe** [comment]
There is a version using cola for its layout in my repository - you can see the demo at:
http://129.215.14.125/ComplexViewer/
(for info - it's in the "deployed" branch of my repo. That branch holds new work, my master branch got out of synch with MICommunity:master and I'm not sure neatest way to get them back in synch)

Anyway - using the cola layout is going to need some further work. In some (most?) cases the layout is worse than the previous one. You can look through the demo examples. Noteworthy ones:

**Shelterin** - better layout
**T-complex** - I think the layout suffers from not having the 'gravity field' that pulls everything into the middle (positioning of atp molecules)
**Core mediator complex** - Fail, doesn't fit on screen. There's issues to do with computing/specifiying the link length it should aim for. (I've looked at this before while using cola with the crosslink viz software, but not found a good solution.)
Hemoglobin - lines always crossed in the middle, darn. Made an issue about it on cola project:
https://github.com/tgdwyer/WebCola/issues/233

Yo (@yochannah) may be able to help as she has been working with cola.
This might be for the next version of ComplexViewer as it might take a bit of work. 

Re. the original issue of bouncing proteins - it is, of course, possible to not render the network while the layout algorithm is still running. I have looked at this before and I think rendering is a small amount of time compared to running the layout algorithm. Hence, the display would be blank for a while as the layout code runs. I previously thought it was better not to do this, it looks broken - the bouncy proteins serve as a sort of '[throbber](https://en.wikipedia.org/wiki/Throbber)'.

**Comment by bmeldal** [comment]
Thanks, Colin.
Yes, I agree, Cola may needs some tweaking.

Bouncing: only 2 people have complained and today's volunteer actually clicked on and opened the protein bars straight away. She may have used the old site before, though!

**Comment by colin-combe** [comment]
OK, there is now a spinner while the layout is computing. No more motion sickness. Also, it checks no labels have ended up over left edge and corrects for it if they have.

You can see a demo at http://complexviewer.org

I'm closing issue now but let me know if there's problems with what I've done,
c
