### ISSUE TITLE
Relative protein circle sizing confusing to users

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#112]
In our standard example of the hemoglobin the protein circles are much smaller than the triangles for the heme molecule which is biologically wrong so the relative sizing of the protein circles backfires. I know it was a bit of a pet-feature of Henning's but I'm still waiting to hear a user say they actually like the relative sizing. Once you open the bar it becomes obvious anyway how big the protein is and to be honest, no-one cares while they are looking at the topology!

**Comment by colin-combe** [comment]
seems like a fair point. 
i'll make them all the same size

**Comment by bmeldal** [comment]
Thanks. We have at least one more test next Monday in case you have a new version by then.

**Comment by colin-combe** [comment]
Changed in MICommunity:master branch so that proteins always have same diameter. 

(Sorry it wasn't in time for today's test.)
