### ISSUE TITLE
slow opening

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#120]
probably to do with calculating layout / spinner

**Comment by bmeldal** [comment]
And the solution might be....

[just asking as I'm teaching on Thursday and will have to apologise for the slowness]

**Comment by colin-combe** [comment]
It seems to be slower when deployed in the Complex Portal than when its outside of it.

I've tried to look and my best guess is that this polyfills library:
http://www.ebi.ac.uk/complexportal/polyfills.6dcf73b7165d80efa59e.bundle.js
is slowing it down. Could be wrong. 

Does it speed up with this library removed?

There's a comment from Josh in the minutes about it being better with d3 version 4?

**Comment by colin-combe** [comment]
hi - 
( @tschaka1904  )
I think better suggestion is to try the version from my master branch (https://github.com/colin-combe/ComplexViewer), it has the spinner disabled.

This way we can find out if it's the spinner itself slowing it down?

**Comment by bmeldal** [comment]
Just a heads up please: I'm teaching this morning so please don't take it down btw 11 am - 12.30 pm!
Thanks,
Birgit

**Comment by tschaka1904** [comment]
I just did benchmarks how long it takes to open: 
http://www.ebi.ac.uk/complexportal/complex/EBI-1202920
http://www.ebi.ac.uk/complexportal/complex/EBI-9691559

and how long it takes on: http://complexviewer.org 

At least for what I can say, they are taking an almost identical amount of time. ...maybe a few ms more or less. 

What I observed, and I think it is a good thing, when you open a complex in a new tab, or you directly navigate to a different tab, the complex viewer will only load when you're on the page. 

I've prepared to clips. One where I'm loading a complex while constantly changing to a different tab. You'll see, that it won't load until I stay at least for a certain amount of time on this page: 

![loading_complexviewer](https://user-images.githubusercontent.com/5269116/30957515-65e537fe-a432-11e7-83f4-b424ae8c3485.gif)

At the other clip, I open the complex and just stay on the page: 
![loading_complexviewer_no_tab_change](https://user-images.githubusercontent.com/5269116/30957572-8ba3d7fc-a432-11e7-93b5-ec70893a5c82.gif)

**Comment by tschaka1904** [comment]
Here is an example that https://www.ebi.ac.uk/complexportal and http://complexviewer.org are very similar in speed:

## Loading EBI-9691559 on complexviewer.org
![load_ebi-9691559_cv](https://user-images.githubusercontent.com/5269116/30958021-c522193e-a433-11e7-8b0f-f38324cdca02.gif)

## Loading EBI-9691559 on complexportal
![load_ebi-9691559_cp](https://user-images.githubusercontent.com/5269116/30958020-c4d5a270-a433-11e7-8c3e-a8a7957b6a2e.gif)

**Comment by tschaka1904** [comment]
Here is an example that https://www.ebi.ac.uk/complexportal and http://complexviewer.org are very similar in speed:

## Loading EBI-9691559 on complexviewer.org
![sep-28-2017 10-05-41](https://user-images.githubusercontent.com/5269116/30958386-db5c8800-a434-11e7-9dff-f4d5cdb18d9c.gif)

## Loading EBI-9691559 on complexportal
![load_ebi-9691559_cp](https://user-images.githubusercontent.com/5269116/30958380-d5198ed4-a434-11e7-9595-2d863cd491ff.gif)

**Comment by colin-combe** [comment]
er, ok, sorry - looked different for me.

Could you try the version from this point in history:
https://github.com/MICommunity/ComplexViewer/tree/9622ebc894ed63fbbd51d2b7a3ccfbaabca83cbc

[ just before spinner was added ]

and check if it really is faster please?

The delay might just seem longer because it is more boring without the seasickness

**Comment by bmeldal** [comment]
While teaching this morning it didn't seem too slow. Maybe something in the background was slowing it down and that 'something' is no gone...?

**Comment by bmeldal** [comment]
I take that back, it's REALLY slow now.

**Comment by colin-combe** [comment]
ok, i think its safe to assume the speed of things at complexviewer.org doesn't change.
So, its someting in the ComplexPortal thats causing the slowdown?

**Comment by tschaka1904** [comment]
@bmeldal could you please write down the complex AC when this happens? This way we can do better benchmarks. It is possible that bigger complexes just take longer and one co-factor is also that we pull data for a lot of other resources. I believe that this is the price for the complex not bouncing around.

**Comment by bmeldal** [comment]
Ok, I'll add it next time I find one hanging.

**Comment by colin-combe** [comment]
I'm trying to upgrade to d3 v4 to see if this speeds things up (apparently it should)... I'm running into some problems due to API changes. Will be in touch when have it working.

**Comment by colin-combe** [comment]
OK, having quite a lot of problems with d3 v4 breaking stuff, (back-pedalling) this change may not happen in the immediate future...   
(@joshkh) Josh - did you say you had tested it with the viewer and it was faster? I just find lots of things broken.

Anyway, I've implemented the solution suggested by Noe: it shows the spinner for the first two seconds then it starts showing the force layout working itself out. It's a compromise. We avoid the violent shaking at the start (and hopefully the worst of the seasickness), but after two seconds there's something to look at, even if its still slightly in motion.

It's in my master branch, demo at complexviewer.org

what do you think?

**Comment by colin-combe** [comment]
going to close, reopen if you see this problem again
