### ISSUE TITLE
MI-Chord: reduce space between arcs

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#129]
There is a lot of white space between the protein arcs in the shelterin example of F6 of the JAMI paper:
https://drive.google.com/file/d/1AA1z_eflmyZBka4i9TAryW2Rf7BR4LjN/view?usp=sharing

I think we can make the protein arcs longer and reduce the white spaces.

Sorry, I don't know what the right repo is!

**Comment by joshkh** [comment]
Moved here: https://github.com/MICommunity/mi-chord/issues/4
