### ISSUE TITLE
Molecule sets look like small molecules and have no name

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#131]
Hi Colin, 

We have now released all yeast complexes but they contain sets as participants which are depicted as triangles in the viewer which are reserved for small molecules.

Are you able to change the symbol to a hexagon and use the shortlabel as name?

e.g. https://www.ebi.ac.uk/complexportal/complex/CPX-1599

Birgit

**Comment by colin-combe** [comment]
Hi Birgit,

> Are you able to change the symbol to a hexagon and use the shortlabel as name?

I'm not sure this is the right thing to do - the hexagon symbol is meant to mean complex (even though this is not currently implemented, #130); a molecule set is something different, right? It's a set of alternatives rather than a higher order aggregation?

How about something like a larger circle with a dashed outline? (Since dashed lines are often associated with uncertainty)

**Comment by bmeldal** [comment]
Sorry, Colin. This should have been 2 issues. I did them quickly before leaving for Easter...

We need to activate the hexagon for complexes and introduce a symbol for sets. I’d suggest a round-edged rectangle for sets to stay in line with Reactome. Reactome’s symbol has a double outline because the dashed one is used in disease pathways.

Does that make sense?

**Comment by colin-combe** [comment]
OK, makes sense

**Comment by colin-combe** [comment]
ok, merged some code into the master branch of MICommunity/ComplexViewer to update the way Molecule Sets are shown.

I did use a double line so the symbol in the legend needs updated in the ComplexPortal.

You can see a demo at complexviewer.org, choose the '40S cytosolic small ribosomal subunit' example (CPX-1599)

let me know if you'd like any changes to the styling of the rectangles

c

**Comment by bmeldal** [comment]
Sets symbols look great!
I see you are working on the complex as participant, too.
