### ISSUE TITLE
Suggested: Upgrade ComplexViewer to a Web Component

### ISSUE THREAD

**Issue by Nikhil-Vats** [MICommunity/ComplexViewer#135]
Hey,

I am implementing ComplexViewer as a Web Component to help users use it on their website easily. It would be very helpful if I can talk to you regarding this.

Thanks,
Nikhil Vats.

**Comment by colin-combe** [comment]
> It would be very helpful if I can talk to you regarding this.

 Please do :) 
We'd be happy to look at merging your changes. You could fork the project so we can see your changes there.

**Comment by Nikhil-Vats** [comment]
Hi Colin,

I just have a bundle.js file which contains all the code. Basically, you can use the component like this - 

![Screenshot 2019-08-20 at 12 39 52 PM](https://user-images.githubusercontent.com/31413407/63325414-ae8bc280-c347-11e9-93e5-41acffe8d056.png)

Almost all the features are implemented, just 2 or 3 are left like annotations.  You can look at the demo [here](https://nikhil-vats.github.io/ComplexViewerWebComponent/index.html).

**Comment by colin-combe** [comment]
@Nikhil-Vats - i didn't see your message of 20 Aug 2019 - sorry, i just missed it or I'd have got in touch.

I've now done something similar using webpack. I'd be interested in what you think of it, and how it compares to what you did.

**Comment by colin-combe** [comment]
i think this can be closed
