### ISSUE TITLE
events for synching with other compnents in page

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#140]
this was also from the 19/07/19 conference call,
to have events that can synchronise ComplexViewer with other components in the web page,
e.g. to inform all components that a certain participant was justed selected.

Can have a think about requirements for this and discuss when i visit

**Comment by colin-combe** [comment]
I updated #106, i guess it was most important since it had its own issue,

let me know if you want to talk about further events for synching with other components in page,
i guess you might want to tie it in with your angular framework - i don't know...

**Comment by bmeldal** [comment]
Any implementation on this will depend on developer time from our side so this ticket is in the "longstay car park" for now ;-)

**Comment by colin-combe** [comment]
I think this was superceeded by more specific issues raised by @Elliot
#159
#160
