### ISSUE TITLE
Not working for really big complexes

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#149]
large complexes burst out of the viewer window:
e.g. https://www.ebi.ac.uk/complexportal/complex/CPX-5183

Not sure if it's on our side, @noedelta ?

**Comment by colin-combe** [comment]
that'll be on my side, I'll see what i can do...

**Comment by bmeldal** [comment]
Another one: https://www.ebi.ac.uk/complexportal/complex/CPX-1627

![image](https://user-images.githubusercontent.com/10517124/84251391-37f1c880-ab05-11ea-9a65-ebcaa4c35a21.png)

Graphic is completely messed up :(

**Comment by colin-combe** [comment]
re. https://www.ebi.ac.uk/complexportal/complex/CPX-1627, it's working for me, looking like this in both chrome and firefox - 
![Screenshot from 2020-06-16 09-35-34](https://user-images.githubusercontent.com/977607/84752007-27ce6300-afb5-11ea-8f79-da23c6091307.png)

@bmeldal - did you change it to make it work? is it working for you now?

i'm onto seeing what can be done about big ones like https://www.ebi.ac.uk/complexportal/complex/CPX-5183

**Comment by bmeldal** [comment]
I think this viewer bug is temperamental. The other day every single complex I opened was off screen but for one participant in the top left corner. I have no idea what's going on. I'll post a screenshot next time it happens again.

**Comment by colin-combe** [comment]
> I think this viewer bug is temperamental.

Yes, upon closer inspection the version of the viewer I left you with after that week at EBI doesn't work properly.

I've been through the code for the whole thing and tidied it up. It was a mess. It still had redundant crud lying around from the original copy and paste of the crosslink viewer code in 2013. I've also updated the build process so it uses webpack and have used automated tools like eslint to check code quality. 

This 'big complexes' issue is one of the things I've looked at.   

Not everything I wanted to address has been addressed - the touch screen issue's not resolved. But I've got such a backlog of crosslinking stuff now i need to stop with this for a bit. I'm sending this message to commit myself to making a pull request today and putting this down for a bit.

**Comment by colin-combe** [comment]
ok... new version at complexviewer.org, prob less wrong with it than previous version

how do you get on with big CPX-5183? (you can resize window and click layout when looking at complexviewer.org to see how it behaves)

if you do see crashes, it's the contents of the javascript console console I need to see not a screenshot. You should be able to get that by pressing control-shift and 'J'. (But until its updated in your websites these aren't really going to be relevant.)

**Comment by colin-combe** [comment]
@bmeldal - you should find that hemeglobin is consistently 'uncrossed' now, 
should be that CPX-1919 is also 'uncrossed' even when its inside CPX-2020 (it wasn't like that before)

**Comment by bmeldal** [comment]
Hi Colin,
Thank you for working on this for a bit.
Expansion looks fine now, at least in the demo version. We'll have to wait and see if @git4anjali can update the viewer on our website soon.
Birgit

**Comment by colin-combe** [comment]
>  We'll have to wait and see if @git4anjali can update the viewer on our website soon.

I think there's a couple of things to fix with it yet, so no rush to update it on websites right now,
cheers,
c

**Comment by colin-combe** [comment]
i'm going to close this in the belief it does now fit in large complexes and a number previous of bugs should have gone away
lets have new issues for new the bugs...

**Comment by bmeldal** [comment]
> i'm going to close this in the belief it does now fit in large complexes and a number previous of bugs should have gone away lets have new issues for new the bugs...

I guess it will still need the update on our side as it's not working right now:

![image](https://user-images.githubusercontent.com/10517124/89414701-c445f380-d722-11ea-815d-d6eaabf4452f.png)

**Comment by colin-combe** [comment]
indeed, you can test it by going to complexviewer.org and varying size of browser window, but its time to update and see which things are fixed / which are broken

**Comment by colin-combe** [comment]
lets update it on ComplexPortal (@git4anjali , @noedelta ), I'm not saying v2 is bug free but I think its a lot better than the version I left you with when I was down visiting this time last year.

It fixes this issue, it may clear these intermittent bugs @bmeldal sees, it allows the 'interacts with complex' case and rings are never crossed over (i.e. hemoglobin always has a square at its centre rather than an extinction rebellion logo)

Its probably only a couple of lines of code - the one where it fetches the complexviewer library and the one where it instantiates it.

I'm totally willing to help... if we don't deploy it we won't find out what bugs it does has

**Comment by colin-combe** [comment]
(i guess in the editor too, i think at the moment people are changing the way things are curated to work around problems in the old version which isn't great)

**Comment by colin-combe** [comment]
@git4anjali , @noe 
- @bmeldal has already found a prob with the layout that should be fixed before we deploy it...

**Comment by colin-combe** [comment]
its probably worth updating it now to stop it doing this
