### ISSUE TITLE
colour scheme key

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#151]
@noe - I added whats meant to be an easier way to create colour scheme keys that include the colours for the complexes, that they're missing is something I mentioned in an email at some point I think...

anyway, i'm getting github fatigue now, I'll keep it brief,

see the index.html for example

**Comment by colin-combe** [comment]
yep, use this to make the colour scheme key and then you'll have the complex colours aswell

**Comment by bmeldal** [comment]
@git4anjali

**Comment by colin-combe** [comment]
I think this is irrelevant now, the way proposed by Eliot is better, 
see #161
