### ISSUE TITLE
don't show annotations from external sources on PRO chains or iso-forms

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#153]
todo - change it so it doesn't show SUPERFAM or UniProtKB annotations on PRO chains or protein isoforms, they won't be in correct place.

for isoforms, the more complete solution would be to fetch the canonical sequence and do a sequence alignment to find out where the annotations should be. To fix for PRO chains fetching the canonical sequence would still be necessary but a complicated alignment procedure would not be

but in meantime just don't show

**Comment by colin-combe** [comment]
an issue was raised with uniprot support to see if there might be a better solution to this

**Comment by colin-combe** [comment]
ok, closed by 2716ab4581131e6f3264cd9d19d7149525cb1919

uniprot & superfam annotations are excluded for things whose id doesn't exactly match uniprot accession (takes out these annotations for isoforms and PRO chains) 

updated it on npm too

this is the version for ComplexPortal, the Editor & IntAct ;)

**Comment by bmeldal** [comment]
Thanks, Colin.
