### ISSUE TITLE
Fire events on protein expansion/collapsing

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#159]
It would be great if Complex Viewer could fire events providing information about the protein that is being collapsed or expanded, especially when it happens on user clicks.

This would allow synchronisation between the viewer and exterior elements such as the participant table in [intact-portal](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-25591088).

Additionally, it would be great if the complexviewer.App could provide getters to know the status (expanded/collapsed) of all the proteins/participants, or one by one given a protein identifier, like `isExpanded(proteinIdentifier: string) -> boolean` and/or `getExpandedParticipants() -> List<string>`. This would help to resynchronise the table checkboxes when users switch back and forth bettween the different tabs.

**Comment by colin-combe** [comment]
has same issue as #160? what do we use as identifier
i guess it would be "use IntAct participant's ac for this function" as with #160 for you

**Comment by EliotRagueneau** [comment]
Yes that would be awesome

**Comment by colin-combe** [comment]
there's a way of adding listeners for this now, example in the index.html file.
there's a function getExpandedParticipants() 
(i didn't do `isExpanded(proteinIdentifier: string) -> boolean` yet)

think main problem here might be that we don't have the identifiers you'd like to use (as for #160)

**Comment by EliotRagueneau** [comment]
I've been using your latest changes on my local version and it's really awesome, its solves almost all of our problem (except the identifier one for now, since we didn't modify the web service yet if I'm not mistaken @noedelta  is on it). 

We found a way to not need the isExpanded function based on the getExpandedParticipants and the listeners, so it's perfect like this. I guess it could still be of good use for all users, but it's not urgent or anything. At least from our point of view at IntAct.

**Comment by colin-combe** [comment]
> We found a way to not need the isExpanded function based on the getExpandedParticipants and the listeners, so it's perfect like this. I guess it could still be of good use for all users, but it's not urgent or anything. 

it might be handy, feel free to add it in yourself if you want. But if its not a priority I guess we won't do this now...

**Comment by EliotRagueneau** [comment]
Maybe when we'll have spare dev time (Not any time soon I'm afraid ...)

Anyway, the problem itself is solved, so I'll mark this issue as solved  😄
