### ISSUE TITLE
Tooltip not showing when annotation underneath AA

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#164]
Sorry to have found a new issue :/

![tooltip](https://user-images.githubusercontent.com/42945601/104581468-8a283880-5656-11eb-81c0-9940c51f3c6f.png)

Basically, when the annotation is underneath the AA sequence, the tooltip does not appear so it's rather hard to see the tooltip for the related annotation. That's not ideal because this usually happens for point mutations, and the patches of colour are so small anyway that it's hard to use the legend to guess which feature it is, so really the tooltip is handy in those cases.

**Comment by colin-combe** [comment]
ok, thanks
