### ISSUE TITLE
Overlapping terminal features are not displayed

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#167]
As you can see on this [page](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-25776165), we have here 2 features located on position c-c (_c-terminus_ and _T4 foldon trimerization domain_), but only one of them is displayed.
We should be able to see as many features as there is, even in the terminal positions, just like it is done on other more regular positions.

The link provided doesn't use the latest release available, but even using the latest release, the problem is still there as you can see in this screenshot:
![Screenshot 2021-03-11 at 11 58 28](https://user-images.githubusercontent.com/42945601/110784057-1a52ba80-8261-11eb-9042-17a757f85b5e.png)

**Comment by colin-combe** [comment]
yup - that'll be right. I knew about this but I never encountered an example that had overlapping terminal features.

i'm looking for it to be updated in the Complex Portal before I do any more work on it, the version that's there is full of bugs/problems so it looks bad when I use it as an example of my work (e.g. grant applications, etc)

E.g. https://www.ebi.ac.uk/complexportal/complex/CPX-5183, it doesn't fit in the panel, fixed that last summer...

let me know if any help is needed with the update :)

**Comment by EliotRagueneau** [comment]
I'm truly sorry about this latency, IntAct is undergoing difficult times with a really low number of devs, and a lot of things to do ...
However,  Noe has integrated your latest changes already., and we are about to publish a testing version of Complex Portal under GitHub pages so that Birgit can test the latest modifications, and if everything is OK, it will be put onto production.

You could expect it under a week or two if there are not too big bugs (normally there aren't 😉 )

Regarding the new IntAct Portal website, my latest changes, including the usage of your latest changes, are not yet under our GitHub pages, but we hope to deliver the website, with those changes, during the month.

 In the meantime, your version 2.0.2 is already used [here](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-8843344), if you want to showcase not so old usage of complexviewer.

**Comment by EliotRagueneau** [comment]
Actually, if you wanna try Complex Portal with your latest changes, Noe just put them under GitHub pages to test them, [so here it is](https://complex-portal.github.io/complex-portal-view/complex/CPX-5183)

**Comment by colin-combe** [comment]
thanks Eliot - i know that was a bit of a grumpy message, it was just getting a bit frustrating doing work on it and then that work not being deployed. And also I know things can be are difficult at the moment.

The new version should still have worked in ComplexPortal with the old way of selection annotation sets, but I see its been changed so that you can select multiple sets of annotations, like on the complexviewer.org page, so thats cool.

I'll get back to you on the overlapping terminal features

**Comment by colin-combe** [comment]
ok, that should be fixed, you can see it at http://complexviewer.org/
let me know if any problems,
cheers,
c

**Comment by EliotRagueneau** [comment]
I just tested it quickly and the tooltip also disappear on the small ticks at the bottom, do you think you could overrule that as well? 
![Screenshot 2021-03-18 at 15 49 11](https://user-images.githubusercontent.com/42945601/111655355-7e492600-8801-11eb-88b9-1b18bb4f8432.png)

**Comment by EliotRagueneau** [comment]
Arf sorry my pointer is not showing up on the picture, but I was hovering over a tick at the bottom of one of the interactions "rulers"

**Comment by colin-combe** [comment]
> tooltip also disappear on the small ticks at the bottom, do you think you could overrule that as well?

yep

**Comment by colin-combe** [comment]
ok, changed it, 
(also minor change to the tooltips of scale bar labels - they don't cause the protein to highlight, instead you see the tooltip for containing complex, don't know if its better or worse? it was sort of by mistake to be honest)

**Comment by EliotRagueneau** [comment]
Better I think ^^ But that's just my opinion.
Thank you very much :D
