### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#174]
i think i see a problem with the layout for https://www.ebi.ac.uk/complexportal/complex/CPX-5684
when the layout first runs, it looks like the the two ACE2 proteins are inside the Spike complex?

it shouldn't do this (i think i might have broken it)

**Comment by bmeldal** [comment]
Yes, you are right, it looks as if ACE2 is now in the Spike subcomplex. Arghhhh!!!!!

Nothing is ever easy with complexes :(

**Comment by colin-combe** [comment]
should be fixed in v2.1.7 (@noedelta),
you can see it at http://complexviewer.org/

**Comment by colin-combe** [comment]
@bmeldal - I think whats shown for CPX-5684 on complexviewer.org (v2.1.8) is perhaps still wrong?

in the json it looks like CPX-5684 has two different participants both with ` "interactorRef": "complex portal_CPX-5682"` (their participant IDs in the json are 26 and 28)

so I think complexviewer is mistakenly merging two separate sub-complex participants into one?

**Comment by colin-combe** [comment]
@bmeldal - i think the above is a bit like https://github.com/MICommunity/ComplexViewer/issues/155#issuecomment-733608143, 
two different subcomplexes end up having exactly the same participants

**Comment by bmeldal** [comment]
Yes, you are right. In ACE2-spike it's a 1:1 ratio, but with the additional protein SLC6A19 it becomes 2:2:2 and the viewer merges the 2 complexes as participants (CPX-5682) into one.

Well, at least it's consistent in it's error ;-)

**Comment by colin-combe** [comment]
yep, i think this is the biggest problem with ComplexVIewer at the moment.

Basically, it can't show more than one instance of the same complex. It's happening because they end up with the same participants, which kind of is how it is in the json.

I think I/we left the previous discussion of this (end of #155) kind of hanging... I said i could fix it in the viewer, you said we should talk again about the json format.

Probably the correct solution to this is changing the json / changing JAMI.

In #155 i said its a problem with the stoichiometry expansion code - it isn't. But it could be addressed with a workaround that does something like the stoichiometry expansion code does (cloning things). I think the things that this workaround couldn't show (linked features between the two different instances of the same complex?) can't be represented in the json at the moment anyway.

I'm happy to look at the viewer workaround if changing JAMI is difficult. What do you think? (@noedelta ? )

**Comment by colin-combe** [comment]
in first instance, we will try the 'cloning' workaround (related #155)

this will have some some shortcomings; i.e. linked features cannot specify which instance of the cloned complex they link to and will appear linked to both

**Comment by colin-combe** [comment]
i made a separate issue just for the 'multiple instances of same complex' problem (#180), so i think this can be closed
