### ISSUE TITLE
position jumps when expanding protein

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#177]
fairly minor thing but doesn't look nice

**Comment by colin-combe** [comment]
@bmeldal noticed this also (#178), it can cause things to jump off the screen so it is a bit of a problem

I've changed it so that proteins stay centred in same place when you change the scale (2.1.13, demo at complexviewer.org) 

But that's also not ideal. I'd like the point you clicked on the bar to stay centred in the same place, but the previous way of doing that was where the problem was coming from, making it work correctly is a bit of a puzzle. So we've got them fixed in place for the time being.

**Comment by bmeldal** [comment]
It stays on screen. I guess close for now and see how it works in reality with random examples.

**Comment by colin-combe** [comment]
ok, keeping the point you clicked at the same location on screen would be better I think, but I'll close for time being,
c
