### ISSUE TITLE
Enable zoom and panning to make big complexes visible even on smaller screens

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#178]
Sometimes when the network/complex is rather big, the font size becomes really small to compensate, which is fine in itself, but at a certain point, especially if you have a small screen horizontally, labels and representations become hard to read because they are too small. 
![Screenshot 2021-05-04 at 22 45 02](https://user-images.githubusercontent.com/42945601/117073817-5fa7db80-ad2a-11eb-9f16-fa2c6b3c5da9.png)
An example of that is the [following network](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-25476274)

A good solution against that could be to grant users the ability to zoom and pan inside the viewer using the mouse wheel like Cytoscape is doing, for instance.

This might be tricky to implement though, I hope, the solution will not be too hard :/

**Comment by EliotRagueneau** [comment]
[This one](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-16264767) is an even better example : 
![Screenshot 2021-05-04 at 22 48 00](https://user-images.githubusercontent.com/42945601/117074085-c927ea00-ad2a-11eb-80a3-e0f0b76d5416.png)

**Comment by colin-combe** [comment]
> This might be tricky to implement though, I hope, the solution will not be too hard :/

It originally had this but I was asked to take it out. Do people definitely want it? Will they want it disabled in ComplexPortal?

**Comment by bmeldal** [comment]
I don't remember being able to zoom within the view but if it was there and we removed it it was probably my fault!

Anyway, I think showing everything and small is good as default as only the really large scale interactions become unreadable and users probably wouldn't be scanning those by eye anyway (they would have to use the tables). But for all other, intermediate cases, zooming in by choice would still be great.

**Comment by colin-combe** [comment]
>I don't remember being able to zoom within the view

it was way back at the start (2013?), pan/zoom is present in the first version of xiNET (http://crosslinkviewer.org) from which complexviewer was derived, but then we took it out of complexviewer. 

anyway...
> zooming in by choice would still be great

OK, I'll put reinstating pan/zoom on the todo list

**Comment by colin-combe** [comment]
discussed this in meeting, intention is to do the zoom 'geometrically' - i.e. everything will get bigger and smaller including the symbols
(unlike the tool at crosslinkviewer.org, where the zooming expands / contracts the space the symbols are in without changing their size )

**Comment by colin-combe** [comment]
@EliotRagueneau - ok, there's pan/zoom in v 2.1.10 (at complexviewer.org)
mousewheel is zoom, you may find find it works on touch screens with the pinch gesture, I haven't tested tbh (it may depend on OS)

a couple of other things to try to help with bigger examples:-
- i added an extra 'scale' option for the bar scales, it may help in some situations if it chooses that as the default scale but I can't be sure, it will depend on things like window size;
- there's a second optional argument for the constructor of complexviewer.App, it gives the maximum number of interactors for which to expand proteins to bar by default. (The default value for this is 4.) It might give you a bit more control than just always calling expandAll().

cheers,
C

**Comment by bmeldal** [comment]
It still doesn't zoom into the bar when you change the scale individually. If you expand them all and there are too many interactors (eg first complex CPX-5684) the AAs and any features are still tiny. 

And for smaller interactions, when you increase the scale from 0.01 to 0.015 to 0.2 it does this: 
![image](https://user-images.githubusercontent.com/10517124/129575242-bec005f7-9619-4a41-899e-d8b43fc8bf97.png)

and pushes the bar far right :(

**Comment by colin-combe** [comment]
Re. the second thing: 
> when you increase the scale from 0.01 to 0.015 to 0.2 it does this:
> [...] and pushes the bar far right :(

yes, you are right, there's a problem there, I never played with the scale menu in that way, I'll fix it.

Re. the first thing:
> It still doesn't zoom into the bar when you change the scale individually. If you expand them all and there are too many interactors (eg first complex CPX-5684) the AAs and any features are still tiny.

I notice the mouse wheel zoom doesn't work if that "Collapse / Scale" context menu is open, but don't you see _everything_ get bigger and smaller when you use the mouse wheel?

**Comment by bmeldal** [comment]
Sorry, yes, mouse wheel - doh! I only have a trackball and trackpad and forgot to use that but yes, it works with the trackpad. Even works with the scale menu open :)

**Comment by colin-combe** [comment]
no prob,
is this what you had in mind when we said 'simple geometric zoom'?

(setting aside the "when you [...] it does this" issue for time being)

**Comment by bmeldal** [comment]
Yes, I think so.

**Comment by colin-combe** [comment]
> when you increase the scale from 0.01 to 0.015 to 0.2 it does this:
> [...] and pushes the bar far right :(

this is the same thing as #177, i'll update that issue and close this
