### ISSUE TITLE
Avoid hatching lines under sequences

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#179]
Hi Colin,

Sometimes, some complexes have non-located features, so they are hatched, and they take the whole width of the sequence (which is totally fine).

However, when this feature is under the sequence, the sequence becomes basically invisible (eg [this network)](https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-1540086). I see 3 solutions against that:

- increase the outline stroke or the background-color of the sequence so that it hides more of the features under him, and enhance the contrast (downside: Might hide the feature under the sequence )
- when possible (several features on the same molecule) make the undefined features come last so that they aren't in the middle (Downside: doesn't really work until there is more than 2 features on a single interaction, which is quite uncommon)
- Consider the sequence as a feature so that the other features dodge it (Downside: will probably not be as well centred and nice ...)

Don't hesitate to discuss the proposed solutions, specially if you find a better one ^^

**Comment by colin-combe** [comment]
> increase the outline stroke

I think that won't work so well because it's not really an outline, its done with a css text shadow:
https://github.com/MICommunity/ComplexViewer/blob/master/src/css/xinet.css#L68

I see there's commented out code to double the size of that text shadow but I think there is a problem with it no longer looking like an outline.

Maybe we could address this by making it a proper outline stroke to the text and making it bigger. 

Other solutions might be switching off the annotations or not using the hatches.

**Comment by bmeldal** [comment]
Good point, Eliot. It does become invisible.

We have quite a few of these features in CP but I never zoomed into them to notice the visualisation issue. Often more than 1  feature with an undefined region.

The non-specific region is actually of no use once you are at the seq level so switching it off as you zoom in might be a neat option. 

I also like the idea that the seq text becomes its own feature.

**Comment by colin-combe** [comment]
> The non-specific region is actually of no use once you are at the seq level so switching it off as you zoom in might be a neat option.

maybe we shouldn't show the non-specific regions that cover the whole sequence on the bars? it would help with this but not completely solve it 

>I also like the idea that the seq text becomes its own feature

that way works if you really do want to see the sequence in the context uncertain features

just getting rid of the hatches and trying to do it all with transparency / colours is going to get a bit confusing with the colours I think

**Comment by colin-combe** [comment]
ok, there is a solution to this in v2.1.10 (currently at complexviewer.org)
the AA letters have a thick white outline, 
it's slightly crude because it just obliterates the sequence annotation colours below, rather than moving them out of the way. 
but it is probably better, prob good enough to close this?

**Comment by bmeldal** [comment]
That works well - except you lost the tooltip with the feature shortlabel :(

**Comment by EliotRagueneau** [comment]
I can still see the tooltip on my side ... That's odd ... 
Otherwise, it's working quite well this outline, the only issue from my side being the N outline that goes outside of its "allowed" area:
![Screenshot 2021-08-16 at 15 06 54](https://user-images.githubusercontent.com/42945601/129577092-e6cd51d6-8404-41bc-ae42-6c2a85449f6a.png)

**Comment by bmeldal** [comment]
Hmm, that is odd. Tooltip works for me in the current CP version but not the demo. My OS is Mac Catalina 10.15.7

**Comment by colin-combe** [comment]
@EliotRagueneau - the spiky N's should be gone (v2.1.12)
@bmeldal - you still have missing tooltips on the Mac?

**Comment by bmeldal** [comment]
I found the tool tip - almost off-screen to the top left!
![image](https://user-images.githubusercontent.com/10517124/129587475-c91af667-b1ca-4077-94a5-77633a66800f.png)

**Comment by colin-combe** [comment]
ok, i see... are all your tooltips there? (i.e. also the ones for the complexes, proteins, links, etc)

**Comment by bmeldal** [comment]
Yes, all of them by the looks of it. And just the bottom left edge visible.

**Comment by EliotRagueneau** [comment]
The issue is present under Firefox and not Chrome

**Comment by bmeldal** [comment]
He he, that old nugget!

**Comment by colin-combe** [comment]
ok, i think you should have tooltips back in firefox?
and those spiky bits on the AA letters should be gone
(v2.1.13, demo at complexviewer.org)

**Comment by bmeldal** [comment]
Yup, tooltip is back!
