### ISSUE TITLE
Proteins still "fly off the screen" when collapsing

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/ComplexViewer#186]
We tested the latest changes from V 2.1.13 but when I expand the protein, move the bar around to find a region near a terminal and then collapse the bar the circle is no longer in the visible part of the screen. I can get it back by either moving the complex until I get to the protein on the edge or by simply refreshing the page (at which point I would lose any other re-arrangements).

e.g. https://intact-portal.github.io/intact-portal-view/details/interaction/EBI-807776

open, expand and collapse URA2.

**Comment by colin-combe** [comment]
ok, i think that's fixed now in v2.1.15
you can test it at complexviewer.org,

cheers,
c

**Comment by EliotRagueneau** [comment]
From what I just tested it now collapses in the middle of the bar when collapsed by the API, which is fine 99% of the time as it also expands from the middle, except when the user moved the bar to a border side and then collapses it from the table, then the middle is off screen. A solution could be  to limit the contraction point to the viewer area when it is not set by the user clicking point

**Comment by bmeldal** [comment]
Works :)

**Comment by colin-combe** [comment]
> which is fine 99% of the time as it also expands from the middle, except when the user moved the bar to a border side and then collapses it from the table, then the middle is off screen. A solution could be to limit the contraction point to the viewer area when it is not set by the user clicking point

ok - i see

**Comment by EliotRagueneau** [comment]
It works perfectly! I'm publishing it to github pages so that Birgit can test as well :D
