### ISSUE TITLE
complexviewer still needs updated on complex portal

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#189]
hi (@EliotRagueneau @git4anjali)
complexviewer still needs updated on complex portal
the version of complexviewer on complex portal is 2.1.6 (March 2021) but the current version is 2.1.16 (October 2021)

most obvious difference is CPX-5684 (SARS-CoV-2 Spike - human ACE2-SLC6A19 complex)
compare first example at complexviewer.org and https://www.ebi.ac.uk/complexportal/complex/CPX-5684
(the complex portal one is wrong) 

col

**Comment by git4anjali** [comment]
Hi Colin,
              Thanks for contacting us about it.

We are heavily under resourced right now. We will try to update as soon as possible but it may take a while.

Thanks&Regards,
Anjali Shrivastava
Senior Software Engineer - IntAct
European Bioinformatics Institute (EMBL-EBI)
South-Building, V3-40,
Wellcome Trust Genome Campus,
Hinxton, Cambridge, UK

Tel: +44 1223 49 4596
E-mail: ***@***.***

**Comment by colin-combe** [comment]
ok, no problem, thanks,
col

**Comment by colin-combe** [comment]
it's updated, thanks 
(@EliotRagueneau)
