### ISSUE TITLE
Flickering of tooltip when dragging expanded node with feature

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#193]
![flickering](https://user-images.githubusercontent.com/42945601/203441672-09e6a5cd-693e-4dd6-bd50-61efefd6fe5b.gif)
When dragging an expanded node with containing a feature, the tooltip is flickering specially when reaching the border of the containing complex

**Comment by colin-combe** [comment]
yep... it looks yucky. I expect we can find a way to stop that...
