### ISSUE TITLE
esbuild compatibility

### ISSUE THREAD

**Issue by EliotRagueneau** [MICommunity/ComplexViewer#204]
I'm upgrading our angular stack on Complex Portal, and I'm trying to use the new esbuild as it is faster and more performant.

However, there are some problems with some imports of the viewer, so I just fixed them in my last commit in order to support them.

Could you please deploy my latest build to npm @colin-combe ?

**Comment by colin-combe** [comment]
ok, done

**Comment by colin-combe** [comment]
> could you redeploy v.2.0.3, or do we need to jump the verison once more?

i'm not sure what you mean - you want to revert to the previous version, which was v2.2.2?

**Comment by EliotRagueneau** [comment]
No no sorry I wasn't clear, basically I commited new changes that I wish to have on complex viewer. Ideally I think we should use the version 2.2.3 as it will not be used for anything else, but if npm doesn't allow you to overwrite an already published version, then we'll need to jump to 2.2.4 I guess

**Comment by colin-combe** [comment]
i see. 
i think it doesn't allow that and we need to go to 2.2.4

**Comment by EliotRagueneau** [comment]
Yes precisely those changes. I do think that we shouldn't have any more problems now, so you can deploy 2.2.4 immediately.

Thank you so much for your quick answer !

**Comment by colin-combe** [comment]
ok, should be done,
this PR will update version number https://github.com/MICommunity/ComplexViewer/pull/205

**Comment by EliotRagueneau** [comment]
It works brilliantly under the github page, should be perfect on the production website.
Thank you so much Colin for these fast deployment, and sorry for the initial request for which I should have more thoroughly tested before asking you to deploy a new version.
