### ISSUE TITLE
shift_click incompatible with tablets

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#75]
The user control to increase scale of protein bar (shift and left click ) is incompatible with tablets.
Compatibility with tablets is a requirement for the Complex Portal. 

Comment from @bmeldal:

> One option I'm thinking off now would be the 2-fingers-pull-apart move to expand a protein bar. That would be more intuitive... 

I'm thinking to tag this with the version 2 milestone...

**Comment by bmeldal** [comment]
Yes, let's get back to using Milestones!

**Comment by colin-combe** [comment]
there's a context menu for choosing the bar scale in the version I just merged.
I think this ends up being better? you can try it and see what you think (complexviewer.org)

@noedelta there some css you need to add to make it work, its here:
https://github.com/MICommunity/ComplexViewer/blob/master/demo/css/XLV.css#L35-L74

**Comment by bmeldal** [comment]
A few examples look broken (some green circle in top left corner but no details visible or clickable, e.g. hemaglobin or telomerase).

The complex jumps around vertically on the page depending on which protein you select and while clicking on the scale menu. We have a new 'sea-sickness' effect :(

Ranges (different ticket?):
The indeterminate ranges (?-?) are now floating around to the left of the bar. The gap becomes bigger on expansion. I think they should be closer.
The tool tips of unlinked ranges floats far below the interaction and may not be visible.

Expand/Collapse:
If fully expanded 'collapse all' can make the complexes completely disappear form the page.

**Comment by colin-combe** [comment]
Er, yes, you're right. I've just merged a broken version.

Bear with me... I'll be back with an updated version in the next couple of days.

**Comment by colin-combe** [comment]
@bmeldal - p.s. which browser/OS are you using? 
I can't replicate all the problems you have...

**Comment by bmeldal** [comment]
That was Firefox for Mac. In Chrome the tooltip stays close and the complex doesn't jump but the ?-? range still floats away from the bar.

Btw: In Firefox the scale menu appears at the top left of the area, not on the protein bar as in Chrome.

**Comment by colin-combe** [comment]
a mistake I made is fixed, so at least all the examples should display now. 

It sounds like there might still be a problem with the new menu for the bar scale. I'll get back to you once I've tested it on a Mac myself. (I should have done this in a separate branch.)

It won't actually work on touch screens at the moment (despite title of issue I have written this under), first thing is to see if we're happy with way it works on desktops. 

re. the floating "?-?", yes, I can see why you don't like the way it looks at the moment. I was playing around with a way to show unlinked features with ?-? position. You can see things like the "Europium label" now, which you couldn't before. 

I'll try and get it so it looks neater but you can still see unlinked ?-? features, unless you really don't want to see these? I was thinking it better represents what's recorded in the data with ?-? features visible.

**Comment by colin-combe** [comment]
@bmeldal - how do you get on with whats at complexviewer.org at moment? 

(somebody else tested it in firefox mac and said it looked like it worked)

**Comment by colin-combe** [comment]
don't have this problem with shift_click now, but I'm not sure what we currently have actually works on touch screens

**Comment by bmeldal** [comment]
The expansion works on touchscreen (I tested on ipad) but you can't move the proteins around so it overlaps and becomes an incoherent mess :(

**Comment by colin-combe** [comment]
_think_ it works on touch screens now, don't have an ipad to test it but it seems to work on an android phone

**Comment by bmeldal** [comment]
Works on my iphone.

**Comment by colin-combe** [comment]
good, lets close it and assume it works on touchscreens 'til we see otherwise

i guess these EBI websites _should_ work on tablets, etc
