### ISSUE TITLE
Show interactions with complex

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#9]
Show interactions with complex (case where interactor ID is the ID of an interaction)

**Comment by colin-combe** [comment]
Sort of working but needs more work / more discussion of how it should work. More examples would be good.

**Comment by bmeldal** [comment]
Ok, this is not yet a practical case as we don't have this data in the release yet. Can me 'Milestone' it or shall we get back to it when we actually have such data? We needs to keep it in the back of our (we'll -  your developer!) minds while planning ahead.

**Comment by bmeldal** [comment]
Oh, and I think it's slightly different to #11.

**Comment by colin-combe** [comment]
Yes, its different to #11. 
What I thought it had in common with #11 is that its not a currently an issue for Complex Portal. 
I'll leave it open and tag with version 2 milestone to indicate "don't forget about this".

I think I read MatrixDB does maintain this kind of hierarchical, "interacts with complex" data

**Comment by bmeldal** [comment]
Yes, MatrixDB indeed use this, but as we currently can't release interactions as interactors we make 'fake' complexes for them as interactors. They are just internally created molecule with a xref to the complex. When we can release complexes/interactions as interactors we can go back and replace those 'placeholder' molecules.
