### ISSUE TITLE
Binding information not available -- so clicking does nothing.

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/ComplexViewer#91]
https://www.ebi.ac.uk/intact/complex/details/EBI-9696567

From Gos (note he was looking at InterMine example, but same issue):

```
In this example if I click on the circles it expands to the what-interacts-with-what 
display but there are no details.  Is there some visual clue that it is worth clicking 
(i.e. there is such data) and/or should one prevent the rectangular display appearing 
if there is no data?  I suppose it does tell you how long the protein is, which could 
be useful but could also be displayed in another way.
```

**Comment by bmeldal** [comment]
Ok, 2 issues:

Even if there are no specifically known binding features, i.e. binding links go from position 1-1 on the partners, there might be info from UniProt or superfamilies when you select the different options in the dropdown menu of the legend, see:
http://www.ebi.ac.uk/intact/complex/details/EBI-8790722
(no binding regions but UniProt features and domain info for a few interactors - expand all to see it clearly)

In the example Gos picked there seems to be a bug, as no UniProt features or domains show up and the 'interactor' option fills in every bar/circle in grey.

@tschaka1904 @colin-combe ???

**Comment by colin-combe** [comment]
yes, there is something going wrong on page Gos chose as an example. It seems to be to do with this error:

Mixed Content: The page at 'https://www.ebi.ac.uk/intact/complex/details/EBI-9696567' was loaded over a secure connection, but contains a form which targets an insecure endpoint ```
'http://www.ebi.ac.uk/intact/complex/'. This endpoint should be made available over a secure connection.
d3.v3.min.js:1 Mixed Content: The page at 'https://www.ebi.ac.uk/intact/complex/details/EBI-9696567' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.uniprot.org/uniprot/Q9BTT4.txt'. This request has been blocked; the content must be served over HTTPS.Cn.i.send @ d3.v3.min.js:1i.(anonymous function) @ d3.v3.min.js:1Cn @ d3.v3.min.js:1(anonymous function) @ d3.v3.min.js:1uniprotWebService @ xiNET_Storage.js:44xiNET_Storage.getUniProtTxt @ 
```

after that all requests to the uniprot web service get blocked for security reasons and things go wrong.

I don't know why this page behaves like this and others don't. 

@tschaka1904 - max, do you get the same error? It seems like its something else in the web page causing it?

**Comment by bmeldal** [comment]
also happens on
http://www.ebi.ac.uk/intact/complex/details/EBI-1245484

They are all really big so maybe something to do with too many interactors to display?

@tschaka1904 I just made an IntAct Jira ticket (CP-36) for this forgetting we had it here, too! I think it's the same issue.

**Comment by tschaka1904** [comment]
@colin-combe yes I get the same error. But I have no idea why.

**Comment by tschaka1904** [comment]
The Mixed Content-error only happens if you use https.

**Comment by colin-combe** [comment]
Re. grey interactors -
yes, I think Birgit might be right - I think I did this deliberately cause there are more types of interactor than distinguishable colours. What happens in this situation needs to be improved.

re. the mixed content error, Max is right, its because the URL used https. It causes uniprot, etc. annotations not to be shown. Should be a seperate issue.

Re gos's original question:

> Is there some visual clue that it is worth clicking 
> (i.e. there is such data)

Yes - the little pie slices in the circles. The start end end angles of these correlate with the start and end residues of the annotated region.

If others accept this as an indication whether clicking is worthwhile then this issue can be closed.

**Comment by bmeldal** [comment]
> Yes - the little pie slices in the circles. The start and end angles of these correlate with the start and end residues of the annotated region.
> If others accept this as an indication whether clicking is worthwhile then this issue can be closed.

When the protein and/or binding region are small or there are many participants the coloured pie slices are difficult to see. Also, usertesting indicated it's not necessarily an invite to click on it. They see the tooltip but don't think there is more 'behind' (that is except for me as my software would click on it by default but I'm not setting the benchmark here!).

**Comment by colin-combe** [comment]
OK - leaving this open.

> "Also, usertesting indicated it's not necessarily an invite to click on it."

I think is a broader problem (people not realising circles can be clicked at all). Making this clearer in the legend was one suggestion regarding how to help with this.

**Comment by colin-combe** [comment]
can reopen if theres still an issue here

**Comment by bmeldal** [comment]
Yes, this has all been fixed via other updates.
