### ISSUE TITLE
Legend - for InterMine

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/ComplexViewer#93]
Is it possible to have the legend on the viewer InterMine is using?

**Comment by colin-combe** [comment]
There are a variety of things you can copy from the projects demo file to get a legend.

The glyphs to make the interactor type table are in /demo/svgForKey.

I have re-enabled code to draw a legend of features/ domain annotations in the SVG and merged it into MIComunity master (its only a change to the index.html demo file), see: https://github.com/MICommunity/interaction-viewer/blob/568197ab9a4055c4e453710219b0fbb16cdc4dcc/index.html#L127-#L162

The code for the html-table-based legend Complex Portal uses is in there also (commented out in the middle of it in a not very tidy way).

**Comment by colin-combe** [comment]
@julie-sullivan did you get a legend?
