### ISSUE TITLE
InterMine - small nuc RNA failing

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/ComplexViewer#94]
From @bmeldal

http://www.humanmine.org/humanmine/report.do?id=37005894&trail=|37005894

> The viewer doesn't open as it has an RNA component.

**Comment by bmeldal** [comment]
It also only displays the 'collapsed' stoichiometry which looks really strange, e.g. Hemoglobin HbA complex (EBI-9008420). If you compare it to the view on the CP, we display the expanded (and therefore biologically more realistic) view but collapse the table to one line per unique molecule with the correct stoichiometry.

**Comment by colin-combe** [comment]
check the type.id attribute of the RNA's interactor in the json you provide the viewer.

I think the behaviour you are getting is because the value of type.id does not appear in this list:
https://github.com/MICommunity/interaction-viewer/blob/master/src/controller/Controller.js#L493-#L505

re. collapsed stoichiometry or not, there is a parameter to the readMiJSON function that tells it whether to expand or not,  but this should default to true.

However, an arbitrary maximum stoichiometry of 30 was imposed and above this it refuses to expand. https://github.com/MICommunity/interaction-viewer/blob/master/src/controller/Controller.js#L395

**Comment by colin-combe** [comment]
Is this still an issue?

**Comment by colin-combe** [comment]
@julie-sullivan is this type of RNA interactor now displaying correctly? Can we close this?

**Comment by colin-combe** [comment]
@bmeldal  - do you know if this is fixed?

**Comment by bmeldal** [comment]
No, still collapses the stoichiometry.

**Comment by colin-combe** [comment]
OK, thanks - though I was really asking about whether this type of RNA molecule now displays correctly. I'll speak to Julie about some of the open issues when we have our next conf call.

**Comment by bmeldal** [comment]
Ok, yes, the viewer opens but the stoichiometry is collapsed. Two conflating issues...

**Comment by julie-sullivan** [comment]
@bmeldal which complex are you looking at? I checked EBI-9016042 and it looks correct to me.

**Comment by bmeldal** [comment]
Ok, so the original bug is fixed: the RNAs display fine in the viewer.
However, they don't show in the table, and neither do small molecules. Are you restricting the table to proteins only?

And there is an issue with the EXPAND function:
E.g. Hemoglobin HbA (EBI-9008420) is collapsed in Intermine but has specifically curated linked features to display the true binding of one heme molecule per protein. It should display as in the CP:
http://www.ebi.ac.uk/intact/complex/details/EBI-9008420
Do you need to update the IntAct files you import? I hand-updated it a while ago.

[NB: the hemoglobin you found, Julie, needs amending, It still displays too many binary links. I'll do that now but it won't show correctly til the next IntAct release is out.]

**Comment by julie-sullivan** [comment]
Yes, we had it constrained to be proteins only. I don't know why but I removed it so they are in the table now.

**Comment by julie-sullivan** [comment]
@bmeldal When did you make these updates? I think we built this database in June. Was it before that?

**Comment by bmeldal** [comment]
Ok, small molecule shows in hemoglobin table :)

I fixed the hemoglobin HbA complex a long time ago, when we started to think about how the viewer is handling stoichiometry expansion and that was when Marine was still here! For this complex you have all 8 molecules in the table but it collapses them to one each in the viewer.

**Comment by julie-sullivan** [comment]
@joshkh if you look at http://www.ebi.ac.uk/intact/complex/details/EBI-9008420 there are eight interactors but each protein is connected to only one small molecule. 

If you look at this complex in InterMine, we have the same interactors but each protein has a line to each small molecule.

How is our JSON different from what the IntAct portal has? I feel like I don't have information about the relationship between each interactor to know to only draw a line to one small molecule.

**Comment by bmeldal** [comment]
> If you look at this complex in InterMine, we have the same interactors but each protein has a line to each small molecule.

No, there are only 3 molecules in the view for EBI-9008420 (Hemoglobin **HbA** complex).

There is another hemoglobin complex, EBI-9016042 (Hemoglobin **HbA2** complex), 
http://www.ebi.ac.uk/intact/complex/details/EBI-9016042
http://www.humanmine.org/humanmine/report.do?id=35002461&trail=|35002461
that has matrix expansion because I curated it *the lazy way* with 3 molecules, 2:2:4 stoichiometry and binding of everything to everyone before we knew what viewer we were going to use and the issues of stoichiometry expansion. I have changed it in our Editor today to display the same way as EBI-9008420 but it won't show up until our next release (before Christmas).

**Comment by julie-sullivan** [comment]
Ah okay! Sorry misunderstood! So I will wait until we get the updated data, and make sure it's correct then.

**Comment by bmeldal** [comment]
Well, there's still an issue with EBI-9008420 which should show a central square of 4 proteins, each of which is connected to one heme... At the moment it just shows a triangle of the three unique interactors each connected to each other but there is a list of all 8 participants (with stoichiometry = 1) in the table.
http://www.ebi.ac.uk/intact/complex/details/EBI-9008420
http://www.humanmine.org/humanmine/report.do?id=35002502&trail=|35002502

**Comment by colin-combe** [comment]
I tried debugging this but can't make much progress because I'm not sure how InterMine loads the data into the viewer. 

Not really sure whats going on - hoping its a problem with the data its being provided. Does the data it receives have the correct stoichiometry values?

**Comment by bmeldal** [comment]
I'm pretty sure IntAct provides the correct JSON as it displays correctly in the viewer in the CP. 

Intermine basically displays the entry directly opposite to the CP: it collapses the stoichiometry in the viewer and expands it to all participants in the table. In the CP we expand in the viewer (until the threshold is reached) and collapse the table so the stoichiometry is easily spotted by the user.

**Comment by colin-combe** [comment]
I can see the 'expand' attribute of the viewer is set to true in InterMine so it shouldn't collapse the stoichiometry. (Also stoich info isn't shown beside the labels in square brackets which indicates it isnt collapsing stoich.)

this is why i'm confused and wondering if stoich info is missing from the JSON?

**Comment by julie-sullivan** [comment]
@colin-combe here is the JSON: http://www.humanmine.org/humanmine/service/complexes/export/EBI-9008420 

The stoich data looks the same to me.

**Comment by colin-combe** [comment]
Yes - stoich is the same. 

here is the problem:

first, the structure of https://www.ebi.ac.uk/intact/complex-ws/export/EBI-9008420
![screenshot from 2016-11-30 14 16 34](https://cloud.githubusercontent.com/assets/977607/20755885/7cd01c12-b708-11e6-915a-58f8d1dd0a1c.png)

now, the structure of  http://www.humanmine.org/humanmine/service/complexes/export/EBI-9008420
![screenshot from 2016-11-30 14 16 50](https://cloud.githubusercontent.com/assets/977607/20755941/c74942e6-b708-11e6-87c7-51cc5a64236e.png)

The intermine JSON only has 3 participants in the interaction whilst the complex portal one has 8.

The intermine JSON also has some funny looking duplication of sequence data and linked feature IDs.

**Comment by colin-combe** [comment]
@julie-sullivan you probably concluded as much, but the import of the data must mix up interactors and participants at some point?

(@bmeldal) Could ask Birgit for other examples of complexes which were manually curated in their expanded form and check if they have same problem in InterMine?

**Comment by bmeldal** [comment]
Yes, it's systemic. Shelterin, EBI-10887677, has the same issue, there are 2xTerf1 and 2xTerf2 but only one each in viewer. You are losing multiple proteins in the viewer if they are hand-expanded with binding features.

Not the case for PCNA, EBI-1202920, which is a homotrimer without binding features and displays as 3 participants on the blue background.

**Comment by julie-sullivan** [comment]
This has moved to the InterMine repo.
