### ISSUE TITLE
Mixed content error if using https

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/ComplexViewer#99]
causes uniprot, etc annotations not to be shown.

Discussed at PSI meeting - best solution might be to let JAMI retrieve the annotations using JAMI-Bridges  and write them in the JSON object we consume. (i.e. move retreiving annotations outside viewer.)

**Comment by joshkh** [comment]
Intermine is moving to HTTPS so we need this as well, and to support the Chord Digram.

**Comment by colin-combe** [comment]
duplicate of #121
